### ISSUE TITLE
Create a "Ways to contribute!" section on the website

### ISSUE THREAD

**Issue by aprilcs** [the-method/the-method.github.io#1]
Below the current Overview section (currently in green) and above the Subscribe to our Mailing List section (currently in light grey), create a new section that gives people ideas of how they can get involved.

The title will be "Ways to contribute!"

There will be 3 parts within the new section, and if you can find pretty icons, that would be lovely too! But text is also fine otherwise. Here is the content of the 3 parts:

**Pick a call**
Our current open calls for contribution are:
1. [Hello World](https://github.com/the-method/podcast/tree/master/010101_Hello_World)
2. [Your Number Ones](https://github.com/the-method/podcast/tree/master/010102_Your_Number_Ones)

**Add your voice**
* Join The Method [WhatsApp Group](https://chat.whatsapp.com/KyvDv4sqc3cHP4enDydZI1) and leave a voice note 
* Leave a voicemail with your contribution at **(929) 367-7330**
* Email a voice memo to **contact.the.method@gmail.com**
* **[Schedule a time](https://beta.doodle.com/methodpodcast)** for The Method to call you 

**Recommend a topic or interview**
[Leave a comment](https://github.com/the-method/podcast/issues/7) recommending someone we should interview, a topic we should explore, or +1 other recommendations

Here is a quick mockup, but please feel free to improve the design and colors as you see fit! Perhaps some of the links should be buttons? 

![newcontributingsection](https://cloud.githubusercontent.com/assets/7356671/26738304/9c9812d8-479b-11e7-87d3-f8b52c7815a5.png)

**Comment by paulvill** [comment]
Hey @aprilcs , I'd be happy to give a try

**Comment by aprilcs** [comment]
Yay! Thanks @paulvill!
